const CART_ACTION_TYPES = {
    SET_CURRENT_DROPDOWN: 'SET_CURRENT_DROPDOWN',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SET_CART_COUNT: 'SET_CART_COUNT',
    SET_CART_TOTAL: 'SET_CART_TOTAL',
}

export default CART_ACTION_TYPES;